export const emojis = {
    grinningFace: "😀",
    grinningFaceWithBigEyes: "😃",
    grinningFaceWithSmilingEyes: "😄",
    beamingFaceWithSmilingEyes: "😁",
    grinningSquintingFace: "😆",
    grinningFaceWithSweat: "😅",
    rollingOnTheFloorLaughing: "🤣",
    faceWithTearsOfJoy: "😂",
    slightlySmilingFace: "🙂",
    upsideDownFace: "🙃",
    winkingFace: "😉",
    smilingFaceWithSmilingEyes: "😊",
    faceBlowingAKiss: "😘",
    kissingFace: "😗",
    kissingFaceWithSmilingEyes: "😙",
    kissingFaceWithClosedEyes: "😚",
    faceSavoringFood: "😋",
    relievedFace: "😌",
    smilingFaceWithSunglasses: "😎",
    smirkingFace: "😏",
    unamusedFace: "😒",
    disappointedFace: "😞",
    worriedFace: "😟",
    frowningFace: "🙁",
    faceWithOpenMouth: "😮",
    hushedFace: "😯",
    surprisedFace: "😲",
    wearyFace: "😩",
    tiredFace: "😫",
    yawningFace: "🥱",
    faceWithSteamFromNose: "😤",
    angryFace: "😠",
    poutingFace: "😡",
    faceWithSymbolsOverMouth: "🤬",
    faceWithSpiralEyes: "😵‍💫",
    faceExploding: "🤯",
    flushedFace: "😳",
    pleadingFace: "🥺",
    faceWithPartyHornAndPartyPopper: "🥳",
    smilingFaceWithHearts: "🥰",
    grinningCatFaceWithSmilingEyes: "😸",
    catFaceWithTearsOfJoy: "😹",
    smilingCatFaceWithHeartEyes: "😻",
    wrySmilingFace: "🤭",
    slightlyFrowningCatFace: "😾",
    cryingCatFace: "😿",
    wearyCatFace: "🙀",
    kissingCatFaceWithClosedEyes: "😽",
    faceWithLookOfTriumph: "😤", // Duplicate with faceWithSteamFromNose
    confusedFace: "😕",
    slightlySmilingFaceWithHalo: "😇",
    devilSmilingFaceWithHorns: "😈",
    angryDevilFace: "👿",
    skull: "💀",
    skullAndCrossbones: "☠️",
    ghost: "👻",
    alien: "👽",
    alienMonster: "👾",
    robotFace: "🤖",
    pileOfPoo: "💩",
    grinningFaceWithSmilingEyesAndHalo: "😇", // Duplicate with smilingFaceWithHalo
    clownFace: "🤡",
    ogre: "👹",
    goblin: "👺",
    jackOLantern: "🎃",
    fire: "🔥",
    sparkles: "✨",
    star: "⭐",
    glowingStar: "🌟",
    dizzySymbol: "💫",
    collision: "💥",
    angerSymbol: "💢",
    sweatDroplets: "💦",
    dashingAway: "💨",
    hole: "🕳️",
    bomb: "💣",
    speechBalloon: "💬",
    thoughtBalloon: "💭",
    zzz: "💤",
    whiteSmilingFace: "😊", // Duplicate with smilingFaceWithSmilingEyes
    slightlySmilingFace2: "🙂", // Duplicate with slightlySmilingFace
    winkingFace2: "😉", // Duplicate with winkingFace
    grinningFaceWithSweat2: "😅", // Duplicate with grinningFaceWithSweat
    faceSavoringFood2: "😋", // Duplicate with faceSavoringFood
    relievedFace2: "😌", // Duplicate with relievedFace
    unamusedFace2: "😒", // Duplicate with unamusedFace
    worriedFace2: "😟", // Duplicate with worriedFace
    frowningFace2: "🙁", // Duplicate with frowningFace
    openMouthFace: "😮", // Duplicate with faceWithOpenMouth
    hushedFace2: "😯", // Duplicate with hushedFace
    astonishedFace: "😲", // Duplicate with surprisedFace
    wearyFace2: "😩", // Duplicate with wearyFace
    tiredFace2: "😫", // Duplicate with tiredFace
    angryFace2: "😠", // Duplicate with angryFace
    poutingFace2: "😡", // Duplicate with poutingFace
    smilingFaceWithHeartEyes2: "😍", // Duplicate with smilingFaceWithHeartEyes
    faceBlowingAKiss2: "😘", // Duplicate with faceBlowingAKiss
    winkingFaceWithTongue: "😜",
    squintingFaceWithTongue: "😝",
    zanyFace: "🤪",
    faceWithRaisedEyebrow2: "🤨", // Duplicate with faceWithRaisedEyebrow
    faceWithMonocle2: "🧐", // Duplicate with faceWithMonocle
    nerdFace2: "🤓", // Duplicate with nerdFace
    thinkingFace2: "🤔", // Duplicate with thinkingFace
    faceWithHeadBandage: "🤕",
    faceWithThermometer: "🤒",
    nauseatedFace: "🤢",
    faceVomiting: "🤮",
    sneezingFace: "🤧",
    hotFace: "🥵",
    coldFace: "🥶",
    woozyFace: "🥴",
    faceWithPleadingEyes: "🥺", // Duplicate with pleadingFace
    partyingFace: "🥳", // Duplicate with faceWithPartyHornAndPartyPopper
    faceWithSmilingEyesAndThreeHearts: "🥰", // Duplicate with smilingFaceWithHearts
    grinningFaceWithSquintingEyes: "😆", // Duplicate with grinningSquintingFace
    faceWithTearsOfJoy2: "😂", // Duplicate with faceWithTearsOfJoy
    slightlySmilingFace3: "🙂", // Duplicate with slightlySmilingFace
    upsideDownFace2: "🙃", // Duplicate with upsideDownFace
    winkingFace3: "😉", // Duplicate with winkingFace
    smilingFaceWithSmilingEyes2: "😊", // Duplicate with smilingFaceWithSmilingEyes
    faceBlowingAKiss3: "😘", // Duplicate with faceBlowingAKiss
    kissingFace2: "😗", // Duplicate with kissingFace
    kissingFaceWithSmilingEyes2: "😙", // Duplicate with kissingFaceWithSmilingEyes
    kissingFaceWithClosedEyes2: "😚", // Duplicate with kissingFaceWithClosedEyes
    faceSavoringFood3: "😋", // Duplicate with faceSavoringFood
    relievedFace3: "😌", // Duplicate with relievedFace
    smilingFaceWithSunglasses2: "😎", // Duplicate with smilingFaceWithSunglasses
    smirkingFace2: "😏", // Duplicate with smirkingFace
    unamusedFace3: "😒", // Duplicate with unamusedFace
    disappointedFace2: "😞", // Duplicate with disappointedFace
    worriedFace3: "😟", // Duplicate with worriedFace
    frowningFace3: "🙁", // Duplicate with frowningFace
    faceWithOpenMouth2: "😮", // Duplicate with faceWithOpenMouth
    hushedFace3: "😯", // Duplicate with hushedFace
    surprisedFace2: "😲", // Duplicate with surprisedFace
    wearyFace3: "😩", // Duplicate with wearyFace
    tiredFace3: "😫", // Duplicate with tiredFace
    angryFace3: "😠", // Duplicate with angryFace
    poutingFace3: "😡", // Duplicate with poutingFace
    smilingFaceWithHeartEyes3: "😍", // Duplicate with smilingFaceWithHeartEyes
    heart: "❤️",
    orangeHeart: "🧡",
    yellowHeart: "💛",
    greenHeart: "💚",
    blueHeart: "💙",
    purpleHeart: "💜",
    brownHeart: "🤎",
    blackHeart: "🖤",
    whiteHeart: "🤍",
    brokenHeart: "💔",
    heartExclamation: "❣",
    twoHearts: "💕",
    revolvingHearts: "💞",
    beatingHeart: "💓",
    growingHeart: "💗",
    sparklingHeart: "💖",
    heartWithArrow: "💘",
    heartWithRibbon: "💝",
    kissMark: "💋",
    lipstick: "💄",
    eyes: "👀",
    eye: "👁️",
    ear: "👂",
    nose: "👃",
    tongue: "👅",
    mouth: "👄",
    baby: "👶",
    child: "🧒",
    boy: "👦",
    girl: "👧",
    person: "🧑",
    man: "👨",
    woman: "👩",
    olderPerson: "🧓",
    oldMan: "👴",
    oldWoman: "👵",
    personWithBlondeHair: "👱",
    manWithBeard: "🧔",
    womanWithHeadscarf: " hijab",
    womanWithTurban: " turban",
    manWithTurban: " man_with_turban",
    policeOfficer: "👮",
    constructionWorker: "👷",
    guard: "💂",
    detective: "🕵️",
    womanHealthWorker: "👩‍⚕️",
    manHealthWorker: "👨‍⚕️",
    womanStudent: "👩‍🎓",
    manStudent: "👨‍🎓",
    womanTeacher: "👩‍🏫",
    manTeacher: "👨‍🏫",
    womanJudge: "👩‍⚖️",
    manJudge: "👨‍⚖️",
    womanFarmer: "👩‍🌾",
    manFarmer: "👨‍🌾",
    womanCook: "👩‍🍳",
    manCook: "👨‍🍳",
    womanMechanic: "👩‍🔧",
    manMechanic: "👨‍🔧",
    womanFactoryWorker: "👩‍🏭",
    manFactoryWorker: "👨‍🏭",
    womanOfficeWorker: "👩‍💼",
    manOfficeWorker: "👨‍💼",
    womanScientist: "👩‍🔬",
    manScientist: "👨‍🔬",
    womanTechnologist: "👩‍💻",
    manTechnologist: "👨‍💻",
    womanSinger: "👩‍🎤",
    manSinger: "👨‍🎤",
    womanArtist: "👩‍🎨",
    manArtist: "👨‍🎨",
    womanPilot: "👩‍✈️",
    manPilot: "👨‍✈️",
    womanAstronaut: "👩‍🚀",
    manAstronaut: "👨‍🚀",
    womanFirefighter: "👩‍🚒",
    manFirefighter: "👨‍🚒",
    womanPoliceOfficer: "👮‍♀️",
    manPoliceOfficer: "👮‍♂️",
    womanDetective: "🕵️‍♀️",
    manDetective: "🕵️‍♂️",
    womanGuard: "💂‍♀️",
    manGuard: "💂‍♂️",
    constructionWorkerWoman: "👷‍♀️",
    constructionWorkerMan: "👷‍♂️",
    personWithCrown: "👑",
    prince: "🤴",
    princess: "👸",
    brideWithVeil: "👰",
    manInTuxedo: "🤵",
    pregnantWoman: "🤰",
    breastFeeding: "🤱",
    angel: "👼",
    santaClaus: "🎅",
    mrsClaus: "🤶",
    superhero: "🦸",
    superheroWoman: "🦸‍♀️",
    superheroMan: "🦸‍♂️",
    supervillain: "🦹",
    supervillainWoman: "🦹‍♀️",
    supervillainMan: "🦹‍♂️",
    mage: "🧙",
    mageWoman: "🧙‍♀️",
    mageMan: "🧙‍♂️",
    fairy: "🧚",
    fairyWoman: "🧚‍♀️",
    fairyMan: "🧚‍♂️",
    vampire: "🧛",
    vampireWoman: "🧛‍♀️",
    vampireMan: "🧛‍♂️",
    zombie: "🧟",
    zombieWoman: "🧟‍♀️",
    zombieMan: "🧟‍♂️",
    genie: "🧞",
    genieWoman: "🧞‍♀️",
    genieMan: "🧞‍♂️",
    merperson: "🧜",
    mermaid: "🧜‍♀️",
    merman: "🧜‍♂️",
    elf: "🧝",
    elfWoman: "🧝‍♀️",
    elfMan: "🧝‍♂️",
    womanWearingTurban: " turbanned_woman",
    manWearingTurban: " turbanned_man",
    personWearingTurban: " person_with_turban",
    womanWithHeadscarf2: " woman_with_headscarf",
    personWithVeil: " 🧕",
    womanWithVeil: " 👰‍♀️",
    manWithVeil: " 🤵‍♂️",
    personGettingMassage: " 💆",
    womanGettingMassage: " 💆‍♀️",
    manGettingMassage: " 💆‍♂️",
    personGettingHaircut: " 💇",
    womanGettingHaircut: " 💇‍♀️",
    manGettingHaircut: " 💇‍♂️",
    personWalking: " 🚶",
    womanWalking: " 🚶‍♀️",
    manWalking: " 🚶‍♂️",
    personRunning: " 🏃",
    womanRunning: " 🏃‍♀️",
    manRunning: " 🏃‍♂️",
    womanDancing: " 💃",
    manDancing: " 🕺",
    personInSuitLevitating: " 🕴️",
    peopleHoldingHands: " 🧑‍🤝‍🧑",
    womanAndManHoldingHands: " 👩‍🤝‍👨",
    twoWomenHoldingHands: " 👩‍🤝‍👩",
    twoMenHoldingHands: " 👨‍🤝‍👨",
    personKneeling: " 🧎",
    womanKneeling: " 🧎‍♀️",
    manKneeling: " 🧎‍♂️",
    personWithWhiteCane: " 🧑‍🦯",
    womanWithWhiteCane: " 👩‍🦯",
    manWithWhiteCane: " 👨‍🦯",
    personInMotorizedWheelchair: " 🧑‍🦼",
    womanInMotorizedWheelchair: " 👩‍🦼",
    manInMotorizedWheelchair: " 👨‍🦼",
    personInManualWheelchair: " 🧑‍🦽",
    womanInManualWheelchair: " 👩‍🦽",
    manInManualWheelchair: " 👨‍🦽",
    personBathing: " 🛀",
    womanBathing: " 🛀", // Gender ambiguous in some sets
    manBathing: " 🛀", // Gender ambiguous in some sets
    personInBed: " 🛌",
    womanLyingInBed: " 🛌", // Gender ambiguous in some sets
    manLyingInBed: " 🛌", // Gender ambiguous in some sets
    peopleWithBunnyEars: " 👯",
    womenWithBunnyEars: " 👯‍♀️",
    menWithBunnyEars: " 👯‍♂️",
    personRaisingHand: " 🙌",
    womanRaisingHand: " 🙌‍♀️",
    manRaisingHand: " 🙌‍♂️",
    personBowing: " 🙇",
    womanBowing: " 🙇‍♀️",
    manBowing: " 🙇‍♂️",
    personFacepalming: " 🤦",
    womanFacepalming: " 🤦‍♀️",
    manFacepalming: " 🤦‍♂️",
    personShrugging: " 🤷",
    womanShrugging: " 🤷‍♀️",
    manShrugging: " 🤷‍♂️",
    personPouting: " 🙎",
    womanPouting: " 🙎‍♀️",
    manPouting: " 🙎‍♂️",
    personFrowning2: "  frown",
    womanFrowning2: " frowning_woman",
    manFrowning2: " frowning_man",
    personSad: " 😥",
    womanSad: " sad_woman",
    manSad: " sad_man",
    personCrying: " 😭",
    womanCrying: " crying_woman",
    manCrying: " crying_man",
    personScreamingInFear: " 😱",
    womanScreamingInFear: " screaming_woman",
    manScreamingInFear: " screaming_man",
    personConfounded: " 😖",
    womanConfounded: " confounded_woman",
    manConfounded: " confounded_man",
    personPersevering: "  persevering_face",
    womanPersevering: " persevering_woman",
    manPersevering: " persevering_man",
    personDisappointedButRelieved: " disappointed_but_relieved_face",
    womanDisappointedButRelieved: " woman_disappointed_but_relieved",
    manDisappointedButRelieved: " man_disappointed_but_relieved",
    personFaceWithOpenMouth2: " face_with_open_mouth",
    womanFaceWithOpenMouth2: " woman_face_with_open_mouth",
    manFaceWithOpenMouth2: " man_face_with_open_mouth",
    personAnguished: " 😫", // Duplicate with anguishedFace
    
}